version: "3.8"
services:
  api:
    container_name: location
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=admin

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  data: {}
  pgadmin-data:
